[build]
  base = "."
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://your-backend-url.onrender.com/api"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://your-backend-url.onrender.com/api"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://your-backend-url.onrender.com/api"
