{
  "services": [
    {
      "type": "web",
      "name": "pharmaexport-backend",
      "env": "node",
      "plan": "free",
      "buildCommand": "cd backend && npm install",
      "startCommand": "cd backend && npm start",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "MONGODB_URI",
          "generateValue": false
        },
        {
          "key": "JWT_SECRET",
          "generateValue": true
        }
      ]
    }
  ]
}
